import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import next from "ultracite/oxlint/next";
import react from "ultracite/oxlint/react";

// Registry components (shadcn, ReUI) are vendored and updated via `shadcn add --diff`.
// The Better Auth schema is regenerated by its CLI (`auth generate`).
const vendored = [
  "packages/ui/src/components/**",
  "packages/db/src/schema/auth.ts",
];

export default defineConfig({
  extends: [core, next, react],
  ignorePatterns: [...(core.ignorePatterns ?? []), ...vendored],
});
