import "server-only";
import { secrets } from "@metobe/db/schema/secrets";
import { systemSettings } from "@metobe/db/schema/system";
import { and, eq, ne } from "drizzle-orm";

import { getDb } from "./db";
import { aadFor, hintFor, open, parseKey, seal } from "./secrets-crypto";
import type { Sealed, SecretsKey } from "./secrets-crypto";

// The one place secrets are written and read (ARCH §17.2). Values are write-only for everyone else: callers get a
// hint, and the plaintext exists only inside `withSecret`'s callback.

export type OwnerType =
  | "system"
  | "source"
  | "catalog_item"
  | "connection"
  | "search_backend"
  | "proxy";
export type Purpose =
  | "api_key"
  | "password"
  | "token"
  | "headers"
  | "oauth_access"
  | "oauth_refresh";
export interface Owner {
  type: OwnerType;
  id: string;
}

let keys: { current: SecretsKey; all: SecretsKey[] } | undefined;

/** SECRETS_KEY encrypts; SECRETS_KEY_PREVIOUS only decrypts, while `metobe secrets:rotate` moves rows over. */
const getKeys = () => {
  if (!keys) {
    const { SECRETS_KEY, SECRETS_KEY_PREVIOUS } = process.env;
    if (!SECRETS_KEY) {
      throw new Error(
        "SECRETS_KEY is not set. It is generated by install.sh; restore it from your .env backup."
      );
    }
    const current = parseKey(SECRETS_KEY);
    keys = {
      all: SECRETS_KEY_PREVIOUS
        ? [current, parseKey(SECRETS_KEY_PREVIOUS)]
        : [current],
      current,
    };
  }
  return keys;
};

/** Stores or replaces a secret; returns the hint the UI may show. */
export const setSecret = async (
  owner: Owner,
  purpose: Purpose,
  value: string,
  expiresAt?: Date
) => {
  const sealed = seal(
    value,
    aadFor(owner.type, owner.id, purpose),
    getKeys().current
  );
  const hint = hintFor(value);
  await getDb()
    .db.insert(secrets)
    .values({
      ...sealed,
      expiresAt,
      hint,
      ownerId: owner.id,
      ownerType: owner.type,
      purpose,
    })
    .onConflictDoUpdate({
      set: {
        ...sealed,
        expiresAt: expiresAt ?? null,
        hint,
        lastUsedAt: null,
        rotatedAt: new Date(),
      },
      target: [secrets.ownerType, secrets.ownerId, secrets.purpose],
    });
  return hint;
};

/**
 * The only read: decrypts right before use and marks the secret used. Returns `null` when there is no secret, so
 * callers decide whether that is an error.
 */
export const withSecret = async <T>(
  owner: Owner,
  purpose: Purpose,
  fn: (value: string) => T | Promise<T>
): Promise<T | null> => {
  const { db } = getDb();
  const where = and(
    eq(secrets.ownerType, owner.type),
    eq(secrets.ownerId, owner.id),
    eq(secrets.purpose, purpose)
  );
  const [row] = await db.select().from(secrets).where(where).limit(1);
  if (!row) {
    return null;
  }
  const value = open(row, aadFor(owner.type, owner.id, purpose), getKeys().all);
  await db
    .update(secrets)
    .set({ lastUsedAt: new Date() })
    .where(eq(secrets.id, row.id));
  return fn(value);
};

/** Hints and status for the UI — never the values. */
export const listSecretHints = (owner: Owner) =>
  getDb()
    .db.select({
      createdAt: secrets.createdAt,
      expiresAt: secrets.expiresAt,
      hint: secrets.hint,
      lastUsedAt: secrets.lastUsedAt,
      purpose: secrets.purpose,
    })
    .from(secrets)
    .where(
      and(eq(secrets.ownerType, owner.type), eq(secrets.ownerId, owner.id))
    );

/** Drops every secret of an owner (disconnecting a source, deleting a proxy). */
export const removeSecrets = async (owner: Owner) => {
  await getDb()
    .db.delete(secrets)
    .where(
      and(eq(secrets.ownerType, owner.type), eq(secrets.ownerId, owner.id))
    );
};

const CANARY = "metobe-secrets-canary";
const canaryAad = aadFor("system", "canary", "canary");

/**
 * Written on first start, checked on every start. A different SECRETS_KEY would otherwise quietly start writing new
 * secrets with it, leaving the database encrypted with two keys at once.
 */
export const ensureSecretsCanary = async () => {
  const { db } = getDb();
  const [row] = await db
    .select({ canary: systemSettings.secretsCanary })
    .from(systemSettings)
    .limit(1);
  if (row?.canary) {
    try {
      if (
        open(JSON.parse(row.canary) as Sealed, canaryAad, getKeys().all) ===
        CANARY
      ) {
        return "ok" as const;
      }
    } catch {
      // Falls through to the explicit message below.
    }
    throw new Error(
      "SECRETS_KEY does not match the key of this installation. Put back the SECRETS_KEY from your .env backup; " +
        "to change the key, keep the old one as SECRETS_KEY_PREVIOUS and run `metobe secrets:rotate`."
    );
  }
  const canary = JSON.stringify(seal(CANARY, canaryAad, getKeys().current));
  await db
    .insert(systemSettings)
    .values({ id: 1, secretsCanary: canary })
    .onConflictDoUpdate({
      set: { secretsCanary: canary },
      target: systemSettings.id,
    });
  return "created" as const;
};

/** Re-encrypts rows written with the previous key, then the canary. Tells whether the old key can go. */
export const rotateSecrets = async () => {
  const { db } = getDb();
  const { current, all } = getKeys();
  // One transaction: a failure halfway must not leave the database split between two keys.
  const rotated = await db.transaction(async (tx) => {
    const stale = await tx
      .select()
      .from(secrets)
      .where(ne(secrets.keyId, current.id));
    await Promise.all(
      stale.map((row) => {
        const aad = aadFor(row.ownerType, row.ownerId, row.purpose);
        const sealed = seal(open(row, aad, all), aad, current);
        return tx
          .update(secrets)
          .set({ ...sealed, rotatedAt: new Date() })
          .where(eq(secrets.id, row.id));
      })
    );
    const [settings] = await tx
      .select({ canary: systemSettings.secretsCanary })
      .from(systemSettings)
      .limit(1);
    if (settings?.canary) {
      const canary = JSON.stringify(
        seal(
          open(JSON.parse(settings.canary) as Sealed, canaryAad, all),
          canaryAad,
          current
        )
      );
      await tx
        .update(systemSettings)
        .set({ secretsCanary: canary })
        .where(eq(systemSettings.id, 1));
    }
    return stale.length;
  });
  return { rotated };
};
