#!/usr/bin/env bash
# Purr installer and updater.
#
#   curl -fsSL https://github.com/artemavrin/purr/releases/latest/download/install.sh | bash
#
# Installs into ./purr (PURR_DIR to change). Running it again updates to the latest release and keeps .env.
# From a git checkout it installs that checkout instead (PURR_BUILD=1 builds the image from source).
#
# Non-interactive: PURR_YES=1 plus PURR_URL, PURR_PORT, PURR_DATABASE_URL, PURR_PROXY, PURR_SMTP_URL as needed.
# Inputs are PURR_-prefixed on purpose: a shell-wide HTTPS_PROXY must not leak into the containers.
set -euo pipefail

# Stamped by the release workflow; empty when running from a git checkout.
PURR_VERSION=""
REPO="artemavrin/purr"

bold=$'\033[1m'; dim=$'\033[2m'; red=$'\033[31m'; green=$'\033[32m'; yellow=$'\033[33m'; off=$'\033[0m'
[ -t 1 ] || { bold=""; dim=""; red=""; green=""; yellow=""; off=""; }

say() { printf '%s\n' "$*"; }
fail() { printf '%sОшибка:%s %s\n' "$red" "$off" "$*" >&2; exit 1; }

# `curl | bash` gives the script stdin, so questions are read from the terminal directly.
tty_in=""
if [ "${PURR_YES:-}" != "1" ] && { exec 3</dev/tty; } 2>/dev/null; then tty_in=3; fi

# ask VAR "question" "default" — keeps a value already set in the environment.
ask() {
  local var="$1" question="$2" default="${3:-}" answer=""
  if [ -n "${!var:-}" ]; then return; fi
  if [ -n "$tty_in" ]; then
    printf '%s %s[%s]%s: ' "$question" "$dim" "${default:-пусто}" "$off" >/dev/tty
    read -r answer <&3 || true
  fi
  printf -v "$var" '%s' "${answer:-$default}"
}

secret() { openssl rand -base64 32 | tr -d '\n'; }
password() { openssl rand -hex 24; }

command -v docker >/dev/null || fail "не найден docker. Установите Docker: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || fail "не найден docker compose v2"
command -v openssl >/dev/null || fail "не найден openssl"

# --- where we install ------------------------------------------------------------------------------
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd || true)"
if [ -z "$PURR_VERSION" ] && [ -f "$script_dir/../compose.yml" ] && [ -f "$script_dir/../docker/Dockerfile" ]; then
  mode="checkout"
  cd "$script_dir/.."
  image="${PURR_IMAGE:-ghcr.io/$REPO:latest}"
else
  mode="release"
  command -v curl >/dev/null || fail "не найден curl"
  if [ -z "$PURR_VERSION" ]; then
    PURR_VERSION="$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" | sed -nE 's/.*"tag_name": *"v?([^"]+)".*/\1/p' | head -1)"
    [ -n "$PURR_VERSION" ] || fail "не удалось узнать последнюю версию Purr"
  fi
  mkdir -p "${PURR_DIR:-purr}"
  cd "${PURR_DIR:-purr}"
  curl -fsSL "https://github.com/$REPO/releases/download/v$PURR_VERSION/compose.yml" -o compose.yml ||
    fail "не удалось скачать compose.yml версии $PURR_VERSION"
  image="ghcr.io/$REPO:$PURR_VERSION"
fi

compose() { docker compose -f compose.yml --env-file .env "$@"; }

say "${bold}Purr${off}${PURR_VERSION:+ $PURR_VERSION} — $(pwd)"
say

# --- .env ------------------------------------------------------------------------------------------
if [ -f .env ]; then
  say "Найден .env — секреты не меняю."
  if grep -q '^PURR_IMAGE=' .env; then
    sed -i.bak "s#^PURR_IMAGE=.*#PURR_IMAGE=$image#" .env && rm -f .env.bak
  else
    echo "PURR_IMAGE=$image" >> .env
  fi
else
  ask PURR_URL "По какому адресу будут открывать Purr" "http://localhost:3000"
  ask PURR_PORT "Порт на этой машине" "3000"
  if [ -z "${PURR_DATABASE_URL:-}" ]; then
    ask PURR_DB_CHOICE "База данных: 1 — встроенная, 2 — своя PostgreSQL" "1"
    if [ "$PURR_DB_CHOICE" = "2" ]; then
      ask PURR_DATABASE_URL "Адрес своей базы (postgres://user:password@host:5432/db)" ""
      [ -n "$PURR_DATABASE_URL" ] || fail "для своей базы нужен адрес"
    fi
  fi
  ask PURR_PROXY "Исходящий прокси, если нужен (http://… или socks5://…)" ""
  ask PURR_SMTP_URL "Почта для писем со входом (smtp://user:pass@host:587), можно позже в настройках" ""

  umask 077
  {
    echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "PURR_IMAGE=$image"
    echo "APP_PORT=$PURR_PORT"
    echo "BETTER_AUTH_URL=$PURR_URL"
    echo "BETTER_AUTH_SECRET=$(secret)"
    echo "# Encrypts provider keys and connection secrets. Losing it makes them unrecoverable."
    echo "SECRETS_KEY=$(secret)"
    if [ -n "${PURR_DATABASE_URL:-}" ]; then
      echo "APP_DATABASE_URL=$PURR_DATABASE_URL"
    else
      echo "COMPOSE_PROFILES=db"
      echo "POSTGRES_PASSWORD=$(password)"
    fi
    [ -z "$PURR_PROXY" ] || echo "HTTPS_PROXY=$PURR_PROXY"
    [ -z "$PURR_SMTP_URL" ] || echo "SMTP_URL=$PURR_SMTP_URL"
  } > .env
  say
  say "${yellow}Сохраните SECRETS_KEY из файла .env в надёжном месте.${off}"
  say "${dim}Без него ключи провайдеров и пароли подключений не восстановить даже из бэкапа.${off}"
fi

# --- image and start -------------------------------------------------------------------------------
build() {
  [ "$mode" = "checkout" ] || fail "не удалось скачать образ $image"
  say "Собираю образ из исходников…"
  docker compose -f compose.yml -f docker/compose.build.yml --env-file .env build --quiet app
}

say
if [ "${PURR_BUILD:-}" = "1" ]; then
  build
elif compose pull --quiet app worker; then
  say "Образ $image скачан."
else
  say "${yellow}Не удалось скачать образ.${off}"
  build
fi
say "Запускаю…"
compose up -d --wait --remove-orphans app worker

link="$(compose exec -T app purr claim-link | grep -oE 'https?://[^ ]+' || true)"
say
say "${green}${bold}Purr запущен.${off}"
if [ -n "$link" ]; then
  say "Создайте аккаунт администратора: ${bold}${link}${off}"
  say "${dim}Ссылка одноразовая и действует 24 часа. Новую выдаст: docker compose exec app purr claim-link${off}"
else
  say "Вход: $(grep -E '^BETTER_AUTH_URL=' .env | cut -d= -f2-)/login"
fi
say "${dim}Обновление: запустите установщик ещё раз в этой же папке.${off}"
