#!/usr/bin/env bash
# Purr installer: asks a few questions, writes .env, starts the stack and prints the claim link.
# Non-interactive: PURR_YES=1 plus PURR_URL, PURR_PORT, PURR_DATABASE_URL, PURR_PROXY, PURR_SMTP_URL as needed.
# Inputs are PURR_-prefixed on purpose: a shell-wide HTTPS_PROXY must not leak into the containers.
set -euo pipefail

cd "$(dirname "$0")/.."

bold=$'\033[1m'; dim=$'\033[2m'; red=$'\033[31m'; green=$'\033[32m'; yellow=$'\033[33m'; off=$'\033[0m'
[ -t 1 ] || { bold=""; dim=""; red=""; green=""; yellow=""; off=""; }

say() { printf '%s\n' "$*"; }
fail() { printf '%sОшибка:%s %s\n' "$red" "$off" "$*" >&2; exit 1; }
interactive() { [ "${PURR_YES:-}" != "1" ] && [ -t 0 ]; }

# ask VAR "question" "default" — keeps a value already set in the environment.
ask() {
  local var="$1" question="$2" default="${3:-}" answer
  if [ -n "${!var:-}" ]; then return; fi
  if interactive; then
    read -r -p "$question ${dim}[${default:-пусто}]${off}: " answer
    printf -v "$var" '%s' "${answer:-$default}"
  else
    printf -v "$var" '%s' "$default"
  fi
}

secret() { openssl rand -base64 32 | tr -d '\n'; }
password() { openssl rand -hex 24; }

command -v docker >/dev/null || fail "не найден docker. Установите Docker: https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || fail "не найден docker compose v2"
command -v openssl >/dev/null || fail "не найден openssl"

compose() { docker compose -f docker/compose.yml --env-file .env "$@"; }

say "${bold}Установка Purr${off}"
say

if [ -f .env ]; then
  say "Найден .env — использую его. Секреты не меняю."
else
  ask PURR_URL "По какому адресу будут открывать Purr" "http://localhost:3000"
  ask PURR_PORT "Порт на этой машине" "3000"
  if [ -z "${PURR_DATABASE_URL:-}" ]; then
    ask PURR_DB_CHOICE "База данных: 1 — встроенная, 2 — своя PostgreSQL" "1"
    if [ "$PURR_DB_CHOICE" = "2" ]; then
      ask PURR_DATABASE_URL "Адрес своей базы (postgres://user:password@host:5432/db)" ""
      [ -n "$PURR_DATABASE_URL" ] || fail "для своей базы нужен адрес"
    fi
  fi
  ask PURR_PROXY "Исходящий прокси, если нужен (http://… или socks5://…)" ""
  ask PURR_SMTP_URL "Почта для писем со входом (smtp://user:pass@host:587), можно позже в настройках" ""

  umask 077
  {
    echo "# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "APP_PORT=$PURR_PORT"
    echo "BETTER_AUTH_URL=$PURR_URL"
    echo "BETTER_AUTH_SECRET=$(secret)"
    echo "# Encrypts provider keys and connection secrets. Losing it makes them unrecoverable."
    echo "SECRETS_KEY=$(secret)"
    if [ -n "${PURR_DATABASE_URL:-}" ]; then
      echo "APP_DATABASE_URL=$PURR_DATABASE_URL"
    else
      echo "COMPOSE_PROFILES=db"
      echo "POSTGRES_PASSWORD=$(password)"
    fi
    [ -z "$PURR_PROXY" ] || echo "HTTPS_PROXY=$PURR_PROXY"
    [ -z "$PURR_SMTP_URL" ] || echo "SMTP_URL=$PURR_SMTP_URL"
  } > .env
  say
  say "${yellow}Сохраните SECRETS_KEY из файла .env в надёжном месте.${off}"
  say "${dim}Без него ключи провайдеров и пароли подключений не восстановить даже из бэкапа.${off}"
fi

say
say "Собираю и запускаю…"
compose build --quiet app
compose up -d --wait app worker

link="$(compose exec -T app purr claim-link | grep -oE 'https?://[^ ]+' || true)"
say
say "${green}${bold}Purr запущен.${off}"
if [ -n "$link" ]; then
  say "Создайте аккаунт администратора: ${bold}${link}${off}"
  say "${dim}Ссылка одноразовая и действует 24 часа. Новую выдаст: docker compose -f docker/compose.yml --env-file .env exec app purr claim-link${off}"
else
  say "Администратор уже создан. Вход: $(grep -E '^BETTER_AUTH_URL=' .env | cut -d= -f2-)/login"
fi
